spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.29.210.211:3306/blog?useSSL=false&serverTimezone=UTC
    username: root
    password: qian654321
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    root: warn
    com.qian.blog: info
  file:
    name: log/blog-pro.log
server:
  port: 80
